### ISSUE TITLE
Import CSV Date/Time NULL

### ISSUE THREAD

**Issue by mheagerty** [pawp81/PBI_OATP#1]
Hi, Thank you so much for this guide. I am hoping you can assist with an issue I am experiencing when trying to import the data into SQL. I have created the database in SQL Express, and added tables via the templates. the Powershell script completes successfully, however the date/time does not import correctly into my table (imports as NULL. See attachment)
My CSV date format is DD/MM/YYYY. Is there a setting i am missing in SQL?
Im sure this is a setting I have missed, so forgive me and thank you in advance
![SQL_DateTime_NULL](https://user-images.githubusercontent.com/70241535/91236522-7baab480-e77b-11ea-8d15-d5ffb5f964c4.PNG)

**Comment by pawp81** [comment]
Hard to say. Is there any error during import to SQL?

**Comment by mheagerty** [comment]
This issue is now resolved. Confirmed that SQL will not accept date format dd/mm/yyyy when importing into the table
Resolved by converting the date format of the exported csv to yyyy/mm/dd
Now working as expected

            $data = Import-Csv -Delimiter "`t" -Path $filepath
            for ($counter=0; $counter -lt $data.Length; $counter++)
            {
                $string_date = $data[$counter].Date
                $date_date = [datetime]::Parse($string_date)
                $data[$counter].Date = $date_date.ToString("yyyy-MM-dd HH:mm:ss")
            }
            $data | Export-Csv -Delimiter "`t" -Path $filepath
